// angular/src/app/shopping-cart/shopping-cart.component.ts
/*
* Program : ShoppingCart component
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from '@angular/core';
import { CategorieService } from 'src/services/categorie.service';
import { ICategorie } from 'src/interfaces/categorie';
import { LocalStorage } from 'src/classes/localstorage';

@Component({
  selector: 'app-shopping-cart',
  templateUrl: './shopping-cart.component.html',
  styleUrls: ['./shopping-cart.component.css']
})
export class ShoppingCartComponent implements OnInit {

  public categories:ICategorie[];
  public shoppingCartCategories:ICategorie[] = [];
  public categorieId:string="";

  constructor(private _categorieService:CategorieService) { }

  ngOnInit() {
       this._categorieService.getCategorieList().subscribe( data => this.categories = data);
  }
  selectCategorie():void
  {
      this.shoppingCartCategories = this.categories.filter(data => data._id.indexOf(this.categorieId) !== -1);
  }
}

<article>
   <form  #shoppingCartForm="ngForm">
        <div class="form-group col-sm-2">
             <label for="categorie">Catégorie {{nomCategorie}}</label>
             <select class="form-control" id="categorie" name="categorie" required #category="ngModel" [(ngModel)]="categorieId" (change)="selectCategorie()">
                     <option [disabled]="true" value="">--Sélectionner--</option>
                     <option *ngFor="let categorie of categories" [value]="categorie._id">{{categorie.nom}}</option>
             </select>
             <div [hidden]="category.valid" class="alert alert-danger">La catégorie est obligatoire</div>
        </div>
        <div class="col-lg-6">
            <app-shopping-cart-basket #shoppingCartBasket></app-shopping-cart-basket>
        </div>
        <div  class="col-lg-12">
            <div class="hpanel hblue" *ngFor="let categorie of shoppingCartCategories | filtreCategory:category.value">
                <div class="panel-heading hbuilt"><strong>{{categorie.nom}}</strong></div>
                <div class="panel-body">
                    <app-shopping-cart-produit [categorieId]='categorie._id' [shoppingCartBasket]="shoppingCartBasket"></app-shopping-cart-produit>
                </div>
            </div>
        </div>
  </form>
</article>

// vue.js/src/components/shoppingCart/index.vue
<template>
    <section id="shopping-cart-index-container">
        <div class="row">
            <div class="col-md-3">
                <div class="hpanel hblue col-md-12">
                    <div class="panel-heading hbuilt"><strong>Sélection</strong></div>
                    <div class="panel-body">
                        <label class="control-label" for="categoryId">Catégories</label>&nbsp;<span style="color:red;">*</span>
                        <select :class="{
                                            input_form_error:!$v.categoryId.$error,
                                            input_form_valid:!$v.categoryId.$invalid,
                                            'form-control':true
                                        }" 
                                    name="categoryId" 
                                    required
                                    v-model.trim="$v.categoryId.$model">
                            <option :disabled="true" value="">--Sélectionner--</option>
                            <option v-for="categorie in categories" :value="categorie._id">{{categorie.nom}}</option>
                        </select>
                        <div v-if="$v.categoryId.$error">
                            <div v-if="!$v.categoryId.required" class="alert alert-danger">Catégorie est obligatoire</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="hpanel hblue col-md-12">
                    <div class="panel-heading hbuilt"><strong>Votre panier</strong></div>
                    <div class="panel-body">
                        <app-shopping-cart-basket ></app-shopping-cart-basket>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="hpanel hblue col-md-12" v-for="categorie in filtreCategorie(categoryId)">
                <div class="panel-heading hbuilt"><strong>{{categorie.nom}}</strong></div>
                <div class="panel-body">
                    <app-shopping-cart-produit v-bind:categoryId="categorie._id"></app-shopping-cart-produit>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
import ShoppingCartProduit from "./shoppingCartProduit";
import ShoppingCartBasket from "./shoppingCartBasket";
import { CategorieService } from "../../services/categorie";
import { ShoppingCartService } from "../../services/shoppingCart";
import { required } from "vuelidate/lib/validators";

export default {
  name: "ShoppingCart",
  components: {
    "app-shopping-cart-produit": ShoppingCartProduit,
    "app-shopping-cart-basket": ShoppingCartBasket
  },
  data() {
    return {
      categories: [],
      shoppingCartData: [],
      carts: [],
      categoryId: "",
      categorieService: new CategorieService(this.$http),
      shoppingCartService: new ShoppingCartService(this.$http)
    };
  },
  created() {
    this.categorieService.categorieListe().then(function(data) {
      var categories = data.body;
      this.categories = categories.length > 0 ? categories : "";
    });

    this.shoppingCartService
      .shoppingCartListe()
      .then(data => (this.shoppingCartData = data.body));
  },
  methods: {
    filtreCategorie(categorieId) {
      if (categorieId) {
        var categorie = this.categories.filter(
          data => data._id.indexOf(categorieId) !== -1
        );
        return categorie.length > 0 ? categorie : "";
      }
    }
  },
  validations: {
    categoryId: {
      required
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
