// angular/src/components/shoppingCart/shopping-cart-produit.component.ts
/*
* Program : ShoppingCartProduit component
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit, Input } from "@angular/core";
import { ShoppingCartService } from "../../services/shoppingCart.service";
import { IProduit } from "../../interfaces/produit";
import { LocalStorage } from "../../classes/localstorage";
import { ShoppingCart } from "../../classes/shoppingcart";
import { ShoppingCartBasketComponent } from "./shopping-cart-basket.component";

@Component({
  selector: "app-shopping-cart-produit",
  templateUrl: "../../views/shoppingCart/shopping-cart-produit.html",
  styles: []
})
export class ShoppingCartProduitComponent implements OnInit {
  @Input()
  categorieId: string;
  @Input()
  shoppingCartBasket: ShoppingCartBasketComponent;

  public shoppingCartList: IProduit[] = [];

  constructor(private _shoppingCartService: ShoppingCartService) {}

  ngOnInit() {}

  ngOnChanges() {
    this._shoppingCartService
      .shoppingCartByCategorieId(this.categorieId)
      .subscribe(
        res => (res !== null ? (this.shoppingCartList = res) : ""),
        err => console.log(err)
      );
  }

  onSubmit(event, shoppingCartId): void {
    let quantite: string = (<HTMLInputElement>(
      document.getElementById(shoppingCartId)
    )).value;
    if (quantite === "") {
      alert("La quantité est obligatoire");
      (<HTMLInputElement>document.getElementById(shoppingCartId)).focus();
      return;
    }
    if (!quantite.match(/^[1-9][0-9]*$/)) {
      alert("La quantité doit être digit et ne contient pas de zéro");
      (<HTMLInputElement>document.getElementById(shoppingCartId)).focus();
      return;
    }
    let carts: Array<ShoppingCart> = [];
    let item: IProduit = this.shoppingCartList.filter(
      data => data.id === parseInt(shoppingCartId)
    )[0];
    let total: number = Number(item.prix) * parseInt(quantite);
    if (!LocalStorage.itemExist("carts")) {
      carts.push(
        new ShoppingCart(
          item.id,
          parseInt(quantite),
          item.prix,
          item.nom,
          total
        )
      );
    } else {
      carts = LocalStorage.getItem("carts");
      let itemTrouve: Array<ShoppingCart> = carts.filter(
        data => data.id === parseInt(shoppingCartId)
      );
      if (itemTrouve.length == 0) {
        carts.push(
          new ShoppingCart(
            item.id,
            parseInt(quantite),
            item.prix,
            item.nom,
            total
          )
        );
      } else {
        carts.map(function(value) {
          if (value.id === parseInt(shoppingCartId)) {
            value.quantite += parseInt(quantite);
            value.total = value.prix * value.quantite;
            return value;
          }
        });
      }
    }
    this.shoppingCartBasket.saveCart(carts);
    event.preventDefault();
  }
}

// vue.js/src/components/shoppingCart/shoppingCartProduit.vue
<template>
    <section>
        <div class="row show-grid" v-if="shoppingCartList(categoryId).length > 0">
            <div class="col-sm-2" style="max-height:220px;" v-for="(shoppingCart,key) in shoppingCartList(categoryId)" v-bind:key="key">
                <div><img src="../../assets/images/placeholder.gif" /></div>
                <div>{{shoppingCart.nom}}</div>
                <div>{{shoppingCart.prix | currency}}</div>
                <div>
                    <input type="text" :id="shoppingCart.id" value="" size="4"/>
                </div><br>
                <div>
                    <button type="submit" class="btn btn-success" @click.prevent="onSubmit($event,shoppingCart.id)">
                        <i class="fa fa-check-square-o" :style="{fontSize:'18px',float:'left'}"></i>
                        <span :style="{marginLeft:'5px',fontWeight:'bold',fontSize:'12px'}">Ajouter</span>
                    </button>
                </div>
            </div>
        </div>
        <div style="color:red;" v-else>Aucun produit a été trouvé</div>
    </section>
</template>

<script>
import { ShoppingCartService } from "../../services/shoppingCart";
import { ShoppingCart } from "../../classes/shoppingCart";
import { LocalStorage } from "../../classes/localstorage";
import { bus } from "../../main";

export default {
  props: {
    categoryId: {
      type: Number,
      required: true
    }
  },
  data() {
    return {
      shoppingCartService: new ShoppingCartService(),
      localStorage: new LocalStorage(),
      shoppingCartData: []
    };
  },
  created() {
    this.shoppingCartService
      .shoppingCartListe()
      .then(
        res =>
          Object.keys(res.body).length > 0
            ? (this.shoppingCartData = res.body)
            : "",
        err => console.log(err)
      );
  },
  methods: {
    shoppingCartList(categorieId) {
      return this.shoppingCartData.filter(
        res => res.categorie_id === parseInt(categorieId)
      );
    },
    onSubmit(event, shoppingCartId) {
      let input = document.getElementById(shoppingCartId);
      let quantite = input.value;
      if (quantite === "") {
        alert("La quantité est obligatoire");
        input.focus();
        return;
      }
      if (!quantite.match(/^[1-9][0-9]*$/)) {
        alert("La quantité doit être digit et ne contient pas de zéro");
        input.value = "";
        input.focus();
        return;
      }
      quantite = parseInt(quantite);
      let carts = [];
      let item = this.shoppingCartData.filter(
        data => data.id === parseInt(shoppingCartId)
      )[0];
      let total = parseFloat(item.prix * quantite).toFixed(2);
      if (!this.localStorage.itemExist("carts")) {
        carts.push(
          new ShoppingCart(item.id, quantite, item.prix, item.nom, total)
        );
      } else {
        carts = this.localStorage.getItem("carts");
        let itemTrouve = carts.filter(
          data => data.id === parseInt(shoppingCartId)
        );
        if (itemTrouve.length == 0) {
          carts.push(
            new ShoppingCart(item.id, quantite, item.prix, item.nom, total)
          );
        } else {
          carts.map(function(value) {
            if (value.id === parseInt(shoppingCartId)) {
              value.quantite += quantite;
              value.total = parseFloat(value.prix * value.quantite).toFixed(2);
              return value;
            }
          });
        }
      }
      bus.$emit("saveCart", carts);
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
