// angular/src/app/file-upload/file-upload.component.ts
/*
* Program : classe FileUploadComponent
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit, Input, Output, EventEmitter, HostListener } from '@angular/core';

@Component({
  selector: 'app-file-upload',
  templateUrl: './file-upload.component.html',
  styleUrls: ['./file-upload.component.css']
})
export class FileUploadComponent implements OnInit {

  errors: Array<string> = [];
  dragAreaClass: string = 'dragarea';
  @Input() name:string;
  @Input() fileExt: string = "JPG, GIF, PNG";
  @Input() maxFiles: number = 5;
  @Input() maxSize: number = 5; // 5MB
  @Output() uploadStatus = new EventEmitter();
  @Output() FileToSave = new EventEmitter();

  constructor() { }

  ngOnInit() {}

  onFileChange(event):void{
         let files = event.target.files;
         this.saveFiles(files);
   }
   saveFiles(files):void
   {
        this.errors = [];
        if (files.length > 0 && !this.isValidFileExtension(files))
        {
            this.uploadStatus.emit(false);
            return;
        }
        if (files.length > 0)
        {
             var reader = new FileReader();
             reader.readAsDataURL(files[0]);
             var that = this;
             reader.onload = function () {
                  that.FileToSave.emit(reader.result);
                  that.uploadStatus.emit(true);
             };
             reader.onerror = function (error) {
                 console.log('Erreur: ', error);
             };
        }
    }
    private isValidFileExtension(files):boolean
    {
        var extensions = (this.fileExt.split(',')).map(function (x) { return x.toLocaleUpperCase().trim() });

        for (var i = 0; i < files.length; i++)
        {
            var ext = files[i].name.toUpperCase().split('.').pop() || files[i].name;
            var exists = extensions.includes(ext);
            if (!exists)
            {
                this.errors.push("Erreur (Extension): " + files[i].name);
            }
            this.isValidFileSize(files[i]);
        }
        return this.errors.length>0?false:true;
    }
    private isValidFileSize(file):void
    {
        var fileSizeinMB = file.size / (1024 * 1000);
        var size = Math.round(fileSizeinMB * 100) / 100; // convert upto 2 decimal place
        if (size > this.maxSize)
            this.errors.push("Erreur (Taille Fichier): " + file.name + ": dépasser la limite de taille de fichier " + this.maxSize + "MB ( " + size + "MB )");
    }
    @HostListener('dragover', ['$event']) onDragOver(event):void
    {
        this.dragAreaClass = "droparea";
        event.preventDefault();
    }
    @HostListener('dragenter', ['$event']) onDragEnter(event):void
    {
        this.dragAreaClass = "droparea";
        event.preventDefault();
    }
    @HostListener('dragend', ['$event']) onDragEnd(event):void
    {
        this.dragAreaClass = "dragarea";
        event.preventDefault();
    }
    @HostListener('dragleave', ['$event']) onDragLeave(event):void
    {
        this.dragAreaClass = "dragarea";
        event.preventDefault();
    }
    @HostListener('drop', ['$event']) onDrop(event):void
    {
        this.dragAreaClass = "dragarea";
        event.preventDefault();
        event.stopPropagation();
        var files = event.dataTransfer.files;
        this.saveFiles(files);
    }
}

<div draggable="true" ngClass="{{dragAreaClass}}">
  <div class="row">
    <div class="col-md-12 text-center" >
      <a href="javascript:void(0)" (click)="file.click()" >
        Sélectionner le fichier
      </a>
        Ou faire glisser le fichier pour télécharger
      <input type="file"
             #file
             (change) = "onFileChange($event)"
             style="display:none" />
    </div>
  </div>
</div><br>
<div class="row error" *ngIf="errors.length > 0">
  <ul>
    <li *ngFor="let err of errors">{{err}}</li>
  </ul>
</div>

// vue.js/src/components/file-upload.vue
<template>
    <div>
        <form enctype="multipart/form-data" novalidate>
            <div class="dropbox">
                <input type="file"
                    :name="uploadFieldName" 
                    @change="filesChange($event.target.name, $event.target.files); 
                    fileCount = $event.target.files.length" accept="image/*" class="input-file">
                <p>Sélectionner le fichier<br>ou faire glisser le fichier pour télécharger</p>
            </div><br>
            <p v-if="errors.length > 0">
                <ul>
                    <li class="error" v-for="error in errors">{{error}}</li>
                </ul>
            </p>
        </form>
    </div>
</template>

<!-- Javascript -->
<script>
const STATUS_SUCCESS = 1, STATUS_FAILED = 0;
export default {
    name: 'fileUpload',
    data () {
        return {
            uploadError: null,
            currentStatus: 0,
            uploadFieldName: 'image',
            errors:[]
        }
    },
    props : {
            maxFiles :{
                type:String,
                required:true
            },
            maxSize : {
                type:String,
                required:true
            },
            fileExt : {
                type:String,
                required:true
            }
    },

    methods: {

        filesChange(fieldName, fileList) 
        {
            this.errors = [];
        
            if(fileList.length > 0 && !this.isValidFileExtension(fileList,this.errors))
            {
                this.$emit('UploadStatus',STATUS_FAILED);
                return;
            }
            
            if(fileList.length > 0)
            {
                var reader = new FileReader();
                reader.readAsDataURL(fileList[0]);
                var that = this;
                reader.onload = function () {
                    that.$emit('UploadStatus',STATUS_SUCCESS);
                    that.$emit('FileToSave',reader.result);
                };
                reader.onerror = function (error) {
                    that.$emit('UploadStatus',STATUS_FAILED);
                    console.log('Erreur: ', error);
                };
            }
        },
        isValidFileExtension(files,errors)
        {
            var extensions = (this.fileExt.split(',')).map(function (x) { return x.toLocaleUpperCase().trim() });
            for (var i = 0; i < files.length; i++) 
            {
                var ext = files[i].name.toUpperCase().split('.').pop() || files[i].name;
                var exists = extensions.includes(ext);

                if (!exists) {
                    errors.push("Erreur (Extension): " + files[i].name);
                }
                this.isValidFileSize(files[i],errors);
            }
            return errors.length > 0?false:true;
        },
        isValidFileSize(file,errors)
        {
            var fileSizeinMB = file.size / (1024 * 1000);
            var size = Math.round(fileSizeinMB * 100) / 100; // convert upto 2 decimal place
            if (size > this.maxSize)
                errors.push("Erreur (Taille Fichier): " + file.name + ": dépasser la limite de taille de fichier " + this.maxSize + "MB ( " + size + "MB )");
        }
    }
    
}
</script>

<!-- SASS styling -->
<style>
.dropbox {
    outline: 2px dashed grey; /* the dash box */
    outline-offset: -10px;
    background: lightcyan;
    color: dimgray;
    padding: 10px 10px;
    min-height: 200px; /* minimum height */
    position: relative;
    cursor: pointer;
  }

  .input-file {
    opacity: 0; /* invisible but it's there! */
    width: 100%;
    height: 200px;
    position: absolute;
    cursor: pointer;
  }

  .dropbox:hover {
    background: lightblue; /* when mouse over to the drop zone, change color */
  }

  .dropbox p {
    font-size: 1.2em;
    text-align: center;
    padding: 50px 0;
  }
</style>
</style>
