// vue.js/src/components/produit/detail.vue
<template>
    <div>
        <article class="col-sm-4">
            <h1>{{titre}} la produit</h1>
            <form v-on:submit.prevent="onSubmit">
                <div class="form-group">
                    <label class="control-label" for="nom">Nom</label>
                    <input class="form-control" name="nom" v-model.trim="$v.model.nom.$model"/>
                    <div v-if="!$v.model.nom.required" class="alert alert-danger">Nom est obligatoire</div>
                    <div v-if="!$v.model.nom.alpha" class="alert alert-danger">Nom contient seulement des caractères</div>
                </div> 
                <div class="form-group">
                    <label class="control-label" for="categorie">Catégories</label>
                    <select class="form-control" name="categorie" v-model.trim="$v.others.categoryId.$model">
                        <option :disabled="true" value="">--Sélectionner--</option>
                        <option v-for="categorie in categories" :value="categorie._id">{{categorie.nom}}</option>
                    </select>
                    <div v-if="!$v.others.categoryId.required" class="alert alert-danger">Catégorie est obligatoire</div> 
                </div>
                <div class="form-group">
                    <label class="control-label" for="founisseurId">Fournisseurs</label>
                    <select class="form-control" name="founisseurId" v-model.trim="$v.others.fournisseurId.$model">
                        <option :disabled="true" value="">--Sélectionner--</option>
                        <option v-for="fournisseur in fournisseurs" :value="fournisseur._id">{{fournisseur.compagnie}}</option>
                    </select>
                    <div v-if="!$v.others.fournisseurId.required" class="alert alert-danger">Fournisseur est obligatoire</div> 
                </div>
                <div class="form-group">
                    <label class="control-label" for="quantite">Quantité</label>
                    <input class="form-control" name="quantite" v-model.trim="$v.model.quantite.$model"/>
                    <div v-if="!$v.model.quantite.required" class="alert alert-danger">Quantité est obligatoire</div>
                    <div v-if="!$v.model.quantite.numeric" class="alert alert-danger">Quantité doit être digit</div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="prix">Prix</label>
                    <input class="form-control" name="prix" v-model.trim="$v.model.prix.$model"/>
                    <div v-if="!$v.model.prix.required" class="alert alert-danger">Prix est obligatoire</div>
                    <div v-if="!$v.model.prix.decimal" class="alert alert-danger">Prix doit être décimal</div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="quantiteRestante">Quantité restante</label>
                    <input class="form-control" name="quantiteRestante" v-model.trim="$v.model.quantiteRestante.$model"/>
                    <div v-if="!$v.model.quantiteRestante.numeric" class="alert alert-danger">Quantité restante doit être digit</div>
                </div> 
                <div class="form-group">
                    <label class="control-label" for="quantiteCommande">Quantité commandée</label>
                    <input class="form-control" name="quantiteCommande" v-model.trim="$v.model.quantiteCommande.$model"/>
                    <div v-if="!$v.model.quantiteCommande.numeric" class="alert alert-danger">Quantité commandée doit être digit</div>
                </div> 
                <div class="form-group">
                    <label class="control-label" for="reapprovisionnement">Réapprovisionnement</label>
                    <input class="form-control" name="reapprovisionnement" v-model.trim="$v.model.reapprovisionnement.$model"/>
                    <div v-if="!$v.model.reapprovisionnement.numeric" class="alert alert-danger">Réapprovisionnement doit être digit</div>
                </div>
                <div class="hpanel hblue">
                    <div class="panel-heading hbuilt"><strong>Discontinue</strong></div>
                    <div class="panel-body" style="height:60px;">
                        <div class="form-group">
                            <label class="form-check-inline" for="discontinue">
                                <input class="form-check-input" type="radio" name="discontinue" :value="true" v-model="model.discontinue">&nbsp;Oui
                            </label>&nbsp;&nbsp;
                            <label class="form-check-inline" for="discontinue">
                                <input class="form-check-input" type="radio" name="discontinue" :value="false" v-model="model.discontinue">&nbsp;Non
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="hidden" class="form-control" id="active" v-model="model.active" name="active">
                </div>
                <button type="submit" class="btn btn-success" :disabled="!$v.model.nom.required 
                                                                         || !$v.model.nom.alpha 
                                                                         || !$v.others.categoryId.required 
                                                                         || !$v.others.fournisseurId.required
                                                                         || !$v.model.quantite.required 
                                                                         || !$v.model.quantite.numeric 
                                                                         || !$v.model.prix.required 
                                                                         || !$v.model.prix.decimal
                                                                         || !$v.model.quantiteRestante.numeric 
                                                                         || !$v.model.quantiteCommande.numeric 
                                                                         || !$v.model.reapprovisionnement.numeric">

                    <i class="fa fa-check-square-o" style="font-size:24px;float:left;"></i>
                    <span style="margin-left:5px;font-weight:bold;font-size:18px;">OK</span>
                </button>&nbsp;
                <button class="btn btn-success" onclick="window.location.href='/admin/produit';return false;">
                    <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                    <span style="margin-left:5px;font-weight:bold;font-size:18px;">BACK</span>
                </button>
            </form>
        </article>
    </div>
</template>

<script>

import { alpha } from '../../inc/helper';
import { required, numeric, decimal } from 'vuelidate/lib/validators';
import { CategorieService } from '../../services/categorie';
import { FournisseurService } from '../../services/fournisseur';
import { ProduitService } from '../../services/produit';
import { Produit } from '../../classes/produit';

export default {
    name: 'ProduitDetail',
    data() 
    {
        return {
            titre : "Ajouter",
            categories : [],
            fournisseurs : [],
            produitService : new ProduitService(this.$http),
            categorieService : new CategorieService(this.$http),
            fournisseurService : new FournisseurService(this.$http),
            model : new Produit(),
            others : { categoryId : "", fournisseurId : ""}
         }
    },
    created()
    {
        this.categorieService.categorieListe().then(function(data)
        {
            var categories = data.body;
            this.categories = categories.length > 0?categories:"";
        });

        this.fournisseurService.fournisseurListe().then(function(data)
        {
            var fournisseurs = data.body;
            this.fournisseurs = fournisseurs.length > 0?fournisseurs:"";
        });

        if(this.$route.params.id)
        { 
            this.titre = "Modifier";
            this.produitService.getProduitById(this.$route.params.id).then(data => this.response(this,data.body));
        }
    },
    methods : {
        response(obj,produits)
        {
            if(typeof produits === 'object')
            {
                this.model = produits;
                this.others.categoryId = produits.category[0]._id;
                this.others.fournisseurId = produits.fournisseur._id;
            }  
        },
        onSubmit()
        {
            var cte = this.categories.filter(data => data._id.indexOf(this.others.categoryId) !== -1);
            var fs = this.fournisseurs.filter(data => data._id.indexOf(this.others.fournisseurId) !== -1);
            
            if(this.$route.params.id)
            {
                this.model.category = cte; 
                this.model.fournisseur = fs[0];
                this.produitService.updateProduit(this.$route.params.id,this.model).then(data => data?this.$router.push({ name: "ListeProduit"}):"");
                return;
            }

            var obj = new Object();
            obj.nom = this.model.nom;
            obj.category = cte;
            obj.fournisseur = fs[0];
            obj.quantite = this.model.quantite;
            obj.prix = this.model.prix;
            obj.quantiteRestante = this.model.quantiteRestante;
            obj.quantiteCommande = this.model.quantiteCommande;
            obj.reapprovisionnement = this.model.reapprovisionnement;
            obj.discontinue = this.model.discontinue;
            obj.dateCreation = this.model.dateCreation;
            obj.active = this.model.active;
            
            this.produitService.saveProduit(obj).then(data => data?this.$router.push({ name: "ListeProduit"}):"");
        }
    },
    validations : {
        model : { 
            nom : {
                required,
                alpha
            },
            quantite : {
                required,
                numeric
            },
            prix : {
                required,
                decimal
            },
            quantiteRestante : {
                numeric
            },
            quantiteCommande : {
                numeric
            },
            reapprovisionnement : {
                numeric
            }
        },
        others : {
             categoryId : {
                 required 
             },
             fournisseurId : {
                 required
             }
        } 
    }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>


</style>

// angular/src/app/produit/detail.component.ts
/*
* Program : Liste des catégories
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from '@angular/core';
import { ProduitService } from 'src/services/produit.service';
import { CategorieService } from 'src/services/categorie.service';
import { FournisseurService } from 'src/services//fournisseur.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Produit } from 'src/classes/produit';
import { Container } from 'src/classes/container';
import { RadioButton } from 'src/classes/radiobutton';
import { IFournisseur } from 'src/interfaces/fournisseur';
import { Regex } from 'src/classes/regex';

@Component({
  selector: 'app-categorie',
  templateUrl: './detail.component.html',
  styles: [ `
               #produitDetail .row
               {
                    margin: 0 0 5px 0;
               }
           `]
})
export class DetailProduitComponent implements OnInit {

  private id:string;
  public titre:string;
  public model:Produit;
  public categories:any[];
  public fournisseurs:any[];
  public digitPattern:string = Regex.DigitPattern();
  public decimalPattern:string = Regex.DecimalPattern();
  public nodigitPattern:string = Regex.NoDigitPattern();
  public categorieId:string = "";
  public fournisseurId:string = "";
  public radioButtonContainer:Container = new Container();

  constructor(
              private _produitService:ProduitService,
              private _categorieService:CategorieService,
              private _fournisseurService:FournisseurService,
              private route: ActivatedRoute,
              private router: Router) {}

  setCategorie(categorieId:string):void
  {
      this.model.category = this.categories.filter(data => data._id.indexOf(categorieId) !== -1);
  }
  setFournisseur(fournisseurId:string):void
  {
      this.model.fournisseur = this.fournisseurs.filter(data => data._id.indexOf(fournisseurId) !== -1)[0];
  }
  ngOnInit()
  {
      this.model = new Produit();
      this.radioButtonContainer.setContainer(new RadioButton('discontinue','Oui','Oui'));
      this.radioButtonContainer.setContainer(new RadioButton('discontinue','Non','Non'));
      this._categorieService.getCategorieList().subscribe( data => this.categories = data );
      this._fournisseurService.getFournisseurList().subscribe( data => this.fournisseurs = data );
      this.id = this.route.snapshot.params.id;
      this.titre = "Ajouter";
      if(this.id)
      {
           this.titre = "Modifier";
           this._produitService.getProduitById(this.id).subscribe(data => this.callback(this,data));
      }
  }
  callback(obj,data):void
  {
      obj.model.nom = data.nom;
      obj.categorieId = data.category[0]._id;
      obj.fournisseurId = data.fournisseur._id;
      obj.model.quantite = data.quantite;
      obj.model.prix = data.prix;
      obj.model.quantiteRestante = data.quantiteRestante;
      obj.model.quantiteCommande = data.quantiteCommande;
      obj.model.reapprovisionnement = data.reapprovisionnement;
      obj.model.discontinue = data.discontinue;
      obj.model.discontinue?this.radioButtonContainer.getContainer()[0].ClsAttribut.checked = true:this.radioButtonContainer.getContainer()[1].ClsAttribut.checked = true;
      obj.model.active = data.active;
  }
  selectCategorie():void
  {
       this.setCategorie(this.categorieId);
  }
  selectFournisseur():void
  {
       this.setFournisseur(this.fournisseurId);
  }
  onSubmit():void
  {
      if(this.id)
      {
            this.setCategorie(this.categorieId);
            this.setFournisseur(this.fournisseurId);
            this._produitService.updateProduit(this.id,this.model)
                                .subscribe(data => data ? this.router.navigateByUrl('/admin/produit'):"");
      }else{
            this._produitService.saveProduit({
                                                nom : this.model.nom,
                                                category:this.model.category,
                                                fournisseur:this.model.fournisseur,
                                                quantite:parseInt(this.model.quantite),
                                                prix:this.model.prix,
                                                quantiteRestante:parseInt(this.model.quantiteRestante),
                                                quantiteCommande:parseInt(this.model.quantiteCommande),
                                                reapprovisionnement:parseInt(this.model.reapprovisionnement),
                                                discontinue:this.model.discontinue,
                                                dateCreation : this.model.dateCreation,
                                                active : this.model.active
                                            })
                                 .subscribe(data => data ? this.router.navigateByUrl('/admin/produit'):"");
        }
   }
}

<article class="col-sm-4">
    <h1>{{titre}} le produit</h1>
    <form (ngSubmit)="onSubmit()" #produitForm="ngForm">
         <div class="form-group">
             <label for="nom">Nom</label>
             <input type="text" class="form-control" id="nom" name="nom" #nom="ngModel" required [(ngModel)]="model.nom" [pattern]="nodigitPattern">
             <div *ngIf="nom.errors">
                   <div [hidden]="!nom.errors.required || nom.pristine" class="alert alert-danger">
                         Nom est obligatoire
                   </div>
                   <div [hidden]="!nom.errors.pattern" class="alert alert-danger">
                         Nom contient seulement des caractères
                   </div>
             </div>
         </div>
         <div class="form-group">
              <label for="categorie">Catégorie</label>
              <select class="form-control" id="categorie" name="categorie" required #category="ngModel" [(ngModel)]="categorieId" (change)="selectCategorie()">
                      <option [disabled]="true" value="">--Sélectionner--</option>
                      <option *ngFor="let categorie of categories" [value]="categorie._id">{{categorie.nom}}</option>
              </select>
              <div [hidden]="category.valid" class="alert alert-danger">Catégorie est obligatoire</div>
         </div>
         <div class="form-group">
              <label for="fournisseur">Fournisseur</label>
              <select class="form-control" id="fournisseur" name="fournisseur" required #supplier="ngModel" [(ngModel)]="fournisseurId" (change)="selectFournisseur()">
                      <option [disabled]="true" value="">--Sélectionner--</option>
                      <option *ngFor="let fournisseur of fournisseurs" [value]="fournisseur._id">{{fournisseur.compagnie}}</option>
              </select>
              <div [hidden]="supplier.valid" class="alert alert-danger">Fournisseur est obligatoire</div>
         </div>
         <div class="form-group">
              <label for="qty">Quantité</label>
              <input type="text" class="form-control" id="qty" name="qty" #qty="ngModel" [(ngModel)]="model.quantite" required [pattern]="digitPattern">
              <div *ngIf="qty.errors">
                    <div [hidden]="!qty.errors.required || qty.pristine" class="alert alert-danger">
              			      Quantité est obligatoire
              			</div>
                    <div [hidden]="!qty.errors.pattern" class="alert alert-danger">
              				    Quantité doit être digit
              			</div>
              </div>
         </div>
         <div class="form-group">
              <label for="prix">Prix</label>
              <input type="text" class="form-control" id="prix" name="prix" #prix="ngModel" [(ngModel)]="model.prix" required [pattern]="decimalPattern">
              <div *ngIf="prix.errors">
                    <div [hidden]="!prix.errors.required || prix.pristine" class="alert alert-danger">
                          Prix est obligatoire
                    </div>
                    <div [hidden]="!prix.errors.pattern" class="alert alert-danger">
                          Prix doit être décimal
                    </div>
              </div>
         </div>
         <div class="form-group">
              <label for="quantiteRestante">Quantité restante</label>
              <input type="text" class="form-control" id="quantiteRestante" name="quantiteRestante" #quantiteRestante="ngModel" [(ngModel)]="model.quantiteRestante" [pattern]="digitPattern">
              <div *ngIf="quantiteRestante.errors">
                  <div [hidden]="!quantiteRestante.errors.pattern" class="alert alert-danger">
                        Quantité restante doit être digit
                  </div>
               </div>
         </div>
         <div class="form-group">
              <label for="quantiteCommande">Quantité commandée</label>
              <input type="text" class="form-control" id="quantiteCommande" name="quantiteCommande" #quantiteCommande="ngModel" [(ngModel)]="model.quantiteCommande" [pattern]="digitPattern">
              <div *ngIf="quantiteCommande.errors">
                  <div [hidden]="!quantiteCommande.errors.pattern" class="alert alert-danger">
                        Quantité de commande doit être digit
                  </div>
              </div>
         </div>
         <div class="form-group">
              <label for="reapprovisionnement">Réapprovisionnement</label>
              <input type="text" class="form-control" id="reapprovisionnement" name="reapprovisionnement" #reapprovisionnement="ngModel" [(ngModel)]="model.reapprovisionnement" [pattern]="digitPattern">
              <div *ngIf="reapprovisionnement.errors">
                  <div [hidden]="!reapprovisionnement.errors.pattern" class="alert alert-danger">
                        Quantité réapprovisionnement doit être digit
                  </div>
              </div>
         </div>
         <div class="hpanel hblue">
               <div class="panel-heading hbuilt"><strong>Discontinue</strong></div>
               <div class="panel-body" style="height:60px;">
                   <div class="form-group">
                      <label class="form-check-inline">
                          <input class="form-check-input" type="radio" name="discontinue" [value]="true" [(ngModel)]="model.discontinue">&nbsp;Oui
                      </label>&nbsp;&nbsp;
                      <label class="form-check-inline">
                           <input class="form-check-input" type="radio" name="discontinue" [value]="false" [(ngModel)]="model.discontinue">&nbsp;Non
                       </label>
                    </div>
               </div>
         </div>
         <button type="submit" class="btn btn-success" [disabled]="!produitForm.form.valid">
                <i class="fa fa-check-square-o" style="font-size:24px;float:left;"></i>
                <span style="margin-left:5px;font-weight:bold;font-size:18px;">OK</span>
         </button>&nbsp;
         <button class="btn btn-success" onclick="window.location.href='/produit';return false;">
                 <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                 <span style="margin-left:5px;font-weight:bold;font-size:18px;">BACK</span>
        </button>
    </form>
</article>
