// vue.js/src/components/product/detail.vue
<template>
    <section id="product-detail-container">
        <form v-on:submit.prevent="onSubmit">
            <div class="row">
                 <div class="col-md-12">
                    <h2><em>{{isAdd?'Ajouter':'Modifier'}} produit</em></h2>
                 </div>
            </div>
            <div class="row">
                <div class="hpanel hblue col-md-4">
                    <div class="panel-heading hbuilt"><strong>Item</strong></div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8">
                                <label class="control-label" for="nom">Nom</label>&nbsp;<span style="color:red;">*</span>
                                <input type="text" 
                                       name="nom" 
                                       v-input-bar-color-error=[!$v.model.nom.$error,!$v.model.nom.$invalid]
                                       required 
                                       v-model.trim="$v.model.nom.$model"/>
                                <div v-if="$v.model.nom.$error && !$v.model.nom.required" class="alert alert-danger">Nom est obligatoire</div>
                                <div v-if="!$v.model.nom.alpha" class="alert alert-danger">Nom contient seulement des caractères</div>
                            </div> 
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <label class="control-label" for="prix">Prix</label>
                                <input type="text" 
                                       name="prix" 
                                       v-input-bar-color-error=[!$v.model.prix.decimal,!$v.model.prix.$invalid]
                                       v-model.trim="$v.model.prix.$model"/>
                                <div v-if="!$v.model.prix.decimal" class="alert alert-danger">Prix doit être décimal</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label class="control-label" for="categorie">Catégories</label>&nbsp;<span style="color:red;">*</span>
                                <select name="categorie" 
                                        v-input-bar-color-error=[true,!$v.model.categorie_id.$invalid]
                                        v-model.trim="$v.model.categorie_id.$model">
                                    <option :disabled="true" value="">--Sélectionner--</option>
                                    <option v-for="categorie in categories" :value="categorie.id">{{categorie.nom}}</option>
                                </select>
                                <div v-if="$v.model.categorie_id.$error && !$v.model.categorie_id.required" class="alert alert-danger">Catégorie est obligatoire</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label class="control-label" for="founisseurId">Fournisseurs</label>&nbsp;<span style="color:red;">*</span>
                                <select  name="founisseurId" 
                                         v-input-bar-color-error=[true,!$v.model.fournisseur_id.$invalid]
                                         v-model.trim="$v.model.fournisseur_id.$model">
                                    <option :disabled="true" value="">--Sélectionner--</option>
                                    <option v-for="fournisseur in fournisseurs" :value="fournisseur.id">{{fournisseur.nom}}</option>
                                </select>
                                <div v-if="$v.model.fournisseur_id.$error && !$v.model.fournisseur_id.required" class="alert alert-danger">Fournisseur est obligatoire</div> 
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7">
                                <label class="control-label" for="reapprovisionnement">Réapprovisionnement</label>
                                <input  type="text"
                                        name="reapprovisionnement"  
                                        v-input-bar-color-error=[!$v.model.reapprovisionnement.numeric,!$v.model.reapprovisionnement.$invalid]
                                        v-model.trim="$v.model.reapprovisionnement.$model"/>
                                <div v-if="!$v.model.reapprovisionnement.numeric" class="alert alert-danger">Réapprovisionnement doit être digit</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="hpanel hblue col-md-4">
                    <div class="panel-heading hbuilt"><strong>Quantité</strong></div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8">
                                <label class="control-label" for="quantiteParUnite">Par unité</label>
                                <input  type="text" 
                                        name="quantiteParUnite" 
                                        class="form-control"
                                        v-model.trim="model.quantiteParUnite"/>
                            </div> 
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <label class="control-label" for="quantite">En stock</label>
                                <input  type="text" 
                                        name="quantite" 
                                        v-input-bar-color-error=[!$v.model.quantiteEnStock.numeric,!$v.model.quantiteEnStock.$invalid]
                                        v-model.trim="$v.model.quantiteEnStock.$model"/>
                                <div v-if="!$v.model.quantiteEnStock.numeric" class="alert alert-danger">Quantité doit être digit</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <label class="control-label" for="quantiteCommande">Commandée</label>
                                <input type="text" 
                                       name="quantiteCommande"
                                       v-input-bar-color-error=[!$v.model.quantiteCommande.numeric,!$v.model.quantiteCommande.$invalid]
                                       v-model.trim="$v.model.quantiteCommande.$model"/>
                                <div v-if="!$v.model.quantiteCommande.numeric" class="alert alert-danger">Quantité commandée doit être digit</div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" v-if="!isAdd">
                <div class="hpanel hblue col-md-4">
                    <div class="panel-heading hbuilt"><strong>Discontinue</strong></div>
                    <div class="panel-body">
                        <span v-for="(radioButton,index) in containerDiscontinueRadioButton">
                            <div :class="radioButton.ClsAttribut" style="position: relative;" @click.prevent="selectedDiscontinueItem(index)">
                                <input type="radio" :name="radioButton.Name" style="position: absolute; opacity: 0;" :value="radioButton.Value">
                                <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;"></ins>
                            </div>&nbsp;{{radioButton.Text}}&nbsp;
                        </span>
                    </div>
                </div>
            </div>
            <div class="row" v-if="!isAdd">
                <div class="hpanel hblue col-md-4">
                    <div class="panel-heading hbuilt"><strong>Active</strong></div>
                    <div class="panel-body">
                        <span v-for="(radioButton,index) in containerActiveRadioButton">
                            <div :class="radioButton.ClsAttribut" style="position: relative;" @click.prevent="selectedActiveItem(index)">
                                <input type="radio" :name="radioButton.Name" style="position: absolute; opacity: 0;" :value="radioButton.Value">
                                <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;"></ins>
                            </div>&nbsp;{{radioButton.Text}}&nbsp;
                        </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <button type="submit" 
                            name="ok"
                            class="btn btn-success" 
                            :disabled="!$v.model.nom.required 
                                      || !$v.model.nom.alpha 
                                      || !$v.model.categorie_id.required 
                                      || !$v.model.fournisseur_id.required
                                      || !$v.model.quantiteEnStock.numeric
                                      || !$v.model.quantiteCommande.numeric 
                                      || !$v.model.prix.decimal
                                      || !$v.model.reapprovisionnement.numeric">
                        <i class="fa fa-check-square-o" style="font-size:24px;float:left;"></i>
                        <span style="margin-left:5px;font-weight:bold;font-size:18px;">OK</span>
                    </button>&nbsp;
                    <button name="back" class="btn btn-success" onclick="window.location.href='/admin/produit';return false;">
                        <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                        <span style="margin-left:5px;font-weight:bold;font-size:18px;">BACK</span>
                    </button>
                    <div class="form-group">
                        <input type="hidden" name="active" class="form-control" id="active" v-model="model.active">
                    </div>
                </div>
            </div>
        </form>
    </section>
</template>

<script>
import { alpha } from "../../inc/helper";
import { required, numeric, decimal } from "vuelidate/lib/validators";
import { CategorieService } from "../../services/categorie";
import { FournisseurService } from "../../services/fournisseur";
import { ProduitService } from "../../services/produit";
import { Produit } from "../../classes/produit";
import { RadioButton } from "../../classes/radioButton";
import { InputBarColorError } from "../../directives/classDirective.js";

export default {
  name: "ProduitDetail",
  data() {
    return {
      isAdd: "",
      categories: [],
      fournisseurs: [],
      produitService: new ProduitService(),
      categorieService: new CategorieService(),
      fournisseurService: new FournisseurService(),
      model: new Produit(),
      radioButton: new RadioButton(),
      containerActiveRadioButton: [],
      containerDiscontinueRadioButton: []
    };
  },
  created() {
    this.isAdd = true;
    this.categorieService
      .categorieListe()
      .then(
        res =>
          Object.keys(res.body).length > 0 ? (this.categories = res.body) : "",
        err => console.log(err)
      );

    this.fournisseurService
      .fournisseurListe()
      .then(
        res =>
          Object.keys(res.body).length > 0
            ? (this.fournisseurs = res.body)
            : "",
        err => console.log(err)
      );

    this.containerDiscontinueRadioButton = [
      new RadioButton("discontinue", "oui", "Oui"),
      new RadioButton("discontinue", "non", "Non")
    ];

    this.containerActiveRadioButton = [
      new RadioButton("active", "oui", "Oui"),
      new RadioButton("active", "non", "Non")
    ];

    if (this.$route.params.id) {
      this.isAdd = false;
      this.produitService.getProduitById(this.$route.params.id).then(
        res => {
          let produit = res.body;
          if (Object.keys(produit).length > 0) {
            this.model.id = produit.id;
            this.model.nom = produit.nom;
            this.model.categorie_id = produit.categorie_id;
            this.model.fournisseur_id = produit.fournisseur_id;
            this.model.quantiteParUnite = produit.quantiteParUnite;
            this.model.prix = produit.prix;
            this.model.quantiteEnStock = produit.quantiteEnStock;
            this.model.quantiteCommande = produit.quantiteCommande;
            this.model.reapprovisionnement = produit.reapprovisionnement;
            this.model.discontinue = produit.discontinue;
            this.model.active = produit.active;
            let containerActiveRadioButton = this.containerActiveRadioButton;
            let containerDiscontinueRadioButton = this
              .containerDiscontinueRadioButton;
            //Le bouton radio discontinue
            if (this.model.discontinue) {
              containerDiscontinueRadioButton[0].clsAttribut =
                containerDiscontinueRadioButton[0].iradioButtonSquare;
            } else {
              containerDiscontinueRadioButton[1].clsAttribut =
                containerDiscontinueRadioButton[1].iradioButtonSquare;
            }
            //Le bouton radio active
            if (this.model.active) {
              containerActiveRadioButton[0].ClsAttribut =
                containerActiveRadioButton[0].iradioButtonSquare;
            } else {
              containerActiveRadioButton[1].ClsAttribut =
                containerActiveRadioButton[1].iradioButtonSquare;
            }
          }
        },
        err => console.log(err)
      );
    }
  },
  methods: {
    selectedDiscontinueItem(index) {
      this.initContainerDiscontinueRadioButton();
      let containerDiscontinueRadioButton = this
        .containerDiscontinueRadioButton;
      containerDiscontinueRadioButton[index].clsAttribut =
        containerDiscontinueRadioButton[index].iradioButtonSquare;
      this.model.discontinue =
        containerDiscontinueRadioButton[index].value === "oui" ? 1 : 0;
    },

    selectedActiveItem(index) {
      this.initActiveRadioButton();
      let containerActiveRadioButton = this.containerActiveRadioButton;
      containerActiveRadioButton[index].ClsAttribut =
        containerActiveRadioButton[index].iradioButtonSquare;
      this.model.active =
        containerActiveRadioButton[index].Value === "oui" ? 1 : 0;
    },

    initContainerDiscontinueRadioButton() {
      for (let radioButton of this.containerDiscontinueRadioButton) {
        radioButton.clsAttribut = radioButton.iradioButtonSquare.split(" ")[0];
      }
    },
    initActiveRadioButton() {
      for (let radioButton of this.containerActiveRadioButton) {
        radioButton.clsAttribut = radioButton.iradioButtonSquare.split(" ")[0];
      }
    },

    onSubmit() {
      if (this.$route.params.id) {
        this.produitService
          .updateProduit(this.model)
          .then(
            res =>
              res.body.success
                ? this.$router.push({ name: "ListeProduit" })
                : alert("Cet item a été sauvegardé avec sans succès"),
            err => console.log(err)
          );
        return;
      }
      this.produitService
        .saveProduit(this.model)
        .then(
          res =>
            res.body.success
              ? this.$router.push({ name: "ListeProduit" })
              : alert("Cet item a été sauvegardé avec sans succès"),
          err => console.log(err)
        );
    }
  },

  validations: {
    model: {
      nom: {
        required,
        alpha
      },
      fournisseur_id: {
        required
      },
      categorie_id: {
        required
      },
      quantiteEnStock: {
        numeric
      },
      prix: {
        decimal
      },
      quantiteCommande: {
        numeric
      },
      reapprovisionnement: {
        numeric
      }
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#product-detail-container .row {
  margin: 0 0 5px 0;
}
</style>

// angular/src/app/produit/detail.component.ts
/*
* Program : Liste des catégories
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from '@angular/core';
import { ProduitService } from 'src/services/produit.service';
import { CategorieService } from 'src/services/categorie.service';
import { FournisseurService } from 'src/services//fournisseur.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Produit } from 'src/classes/produit';
import { Container } from 'src/classes/container';
import { RadioButton } from 'src/classes/radiobutton';
import { IFournisseur } from 'src/interfaces/fournisseur';
import { Regex } from 'src/classes/regex';

@Component({
  selector: 'app-categorie',
  templateUrl: './detail.component.html',
  styles: [ `
               #produitDetail .row
               {
                    margin: 0 0 5px 0;
               }
           `]
})
export class DetailProduitComponent implements OnInit {

  private id:string;
  public titre:string;
  public model:Produit;
  public categories:any[];
  public fournisseurs:any[];
  public digitPattern:string = Regex.DigitPattern();
  public decimalPattern:string = Regex.DecimalPattern();
  public nodigitPattern:string = Regex.NoDigitPattern();
  public categorieId:string = "";
  public fournisseurId:string = "";
  public radioButtonContainer:Container = new Container();

  constructor(
              private _produitService:ProduitService,
              private _categorieService:CategorieService,
              private _fournisseurService:FournisseurService,
              private route: ActivatedRoute,
              private router: Router) {}

  setCategorie(categorieId:string):void
  {
      this.model.category = this.categories.filter(data => data._id.indexOf(categorieId) !== -1);
  }
  setFournisseur(fournisseurId:string):void
  {
      this.model.fournisseur = this.fournisseurs.filter(data => data._id.indexOf(fournisseurId) !== -1)[0];
  }
  ngOnInit()
  {
      this.model = new Produit();
      this.radioButtonContainer.setContainer(new RadioButton('discontinue','Oui','Oui'));
      this.radioButtonContainer.setContainer(new RadioButton('discontinue','Non','Non'));
      this._categorieService.getCategorieList().subscribe( data => this.categories = data );
      this._fournisseurService.getFournisseurList().subscribe( data => this.fournisseurs = data );
      this.id = this.route.snapshot.params.id;
      this.titre = "Ajouter";
      if(this.id)
      {
           this.titre = "Modifier";
           this._produitService.getProduitById(this.id).subscribe(data => this.callback(this,data));
      }
  }
  callback(obj,data):void
  {
      obj.model.nom = data.nom;
      obj.categorieId = data.category[0]._id;
      obj.fournisseurId = data.fournisseur._id;
      obj.model.quantite = data.quantite;
      obj.model.prix = data.prix;
      obj.model.quantiteRestante = data.quantiteRestante;
      obj.model.quantiteCommande = data.quantiteCommande;
      obj.model.reapprovisionnement = data.reapprovisionnement;
      obj.model.discontinue = data.discontinue;
      obj.model.discontinue?this.radioButtonContainer.getContainer()[0].ClsAttribut.checked = true:this.radioButtonContainer.getContainer()[1].ClsAttribut.checked = true;
      obj.model.active = data.active;
  }
  selectCategorie():void
  {
       this.setCategorie(this.categorieId);
  }
  selectFournisseur():void
  {
       this.setFournisseur(this.fournisseurId);
  }
  onSubmit():void
  {
      if(this.id)
      {
            this.setCategorie(this.categorieId);
            this.setFournisseur(this.fournisseurId);
            this._produitService.updateProduit(this.id,this.model)
                                .subscribe(data => data ? this.router.navigateByUrl('/admin/produit'):"");
      }else{
            this._produitService.saveProduit({
                                                nom : this.model.nom,
                                                category:this.model.category,
                                                fournisseur:this.model.fournisseur,
                                                quantite:parseInt(this.model.quantite),
                                                prix:this.model.prix,
                                                quantiteRestante:parseInt(this.model.quantiteRestante),
                                                quantiteCommande:parseInt(this.model.quantiteCommande),
                                                reapprovisionnement:parseInt(this.model.reapprovisionnement),
                                                discontinue:this.model.discontinue,
                                                dateCreation : this.model.dateCreation,
                                                active : this.model.active
                                            })
                                 .subscribe(data => data ? this.router.navigateByUrl('/admin/produit'):"");
        }
   }
}

<article class="col-sm-4">
    <h1>{{titre}} le produit</h1>
    <form (ngSubmit)="onSubmit()" #produitForm="ngForm">
         <div class="form-group">
             <label for="nom">Nom</label>
             <input type="text" class="form-control" id="nom" name="nom" #nom="ngModel" required [(ngModel)]="model.nom" [pattern]="nodigitPattern">
             <div *ngIf="nom.errors">
                   <div [hidden]="!nom.errors.required || nom.pristine" class="alert alert-danger">
                         Nom est obligatoire
                   </div>
                   <div [hidden]="!nom.errors.pattern" class="alert alert-danger">
                         Nom contient seulement des caractères
                   </div>
             </div>
         </div>
         <div class="form-group">
              <label for="categorie">Catégorie</label>
              <select class="form-control" id="categorie" name="categorie" required #category="ngModel" [(ngModel)]="categorieId" (change)="selectCategorie()">
                      <option [disabled]="true" value="">--Sélectionner--</option>
                      <option *ngFor="let categorie of categories" [value]="categorie._id">{{categorie.nom}}</option>
              </select>
              <div [hidden]="category.valid" class="alert alert-danger">Catégorie est obligatoire</div>
         </div>
         <div class="form-group">
              <label for="fournisseur">Fournisseur</label>
              <select class="form-control" id="fournisseur" name="fournisseur" required #supplier="ngModel" [(ngModel)]="fournisseurId" (change)="selectFournisseur()">
                      <option [disabled]="true" value="">--Sélectionner--</option>
                      <option *ngFor="let fournisseur of fournisseurs" [value]="fournisseur._id">{{fournisseur.compagnie}}</option>
              </select>
              <div [hidden]="supplier.valid" class="alert alert-danger">Fournisseur est obligatoire</div>
         </div>
         <div class="form-group">
              <label for="qty">Quantité</label>
              <input type="text" class="form-control" id="qty" name="qty" #qty="ngModel" [(ngModel)]="model.quantite" required [pattern]="digitPattern">
              <div *ngIf="qty.errors">
                    <div [hidden]="!qty.errors.required || qty.pristine" class="alert alert-danger">
              			      Quantité est obligatoire
              			</div>
                    <div [hidden]="!qty.errors.pattern" class="alert alert-danger">
              				    Quantité doit être digit
              			</div>
              </div>
         </div>
         <div class="form-group">
              <label for="prix">Prix</label>
              <input type="text" class="form-control" id="prix" name="prix" #prix="ngModel" [(ngModel)]="model.prix" required [pattern]="decimalPattern">
              <div *ngIf="prix.errors">
                    <div [hidden]="!prix.errors.required || prix.pristine" class="alert alert-danger">
                          Prix est obligatoire
                    </div>
                    <div [hidden]="!prix.errors.pattern" class="alert alert-danger">
                          Prix doit être décimal
                    </div>
              </div>
         </div>
         <div class="form-group">
              <label for="quantiteRestante">Quantité restante</label>
              <input type="text" class="form-control" id="quantiteRestante" name="quantiteRestante" #quantiteRestante="ngModel" [(ngModel)]="model.quantiteRestante" [pattern]="digitPattern">
              <div *ngIf="quantiteRestante.errors">
                  <div [hidden]="!quantiteRestante.errors.pattern" class="alert alert-danger">
                        Quantité restante doit être digit
                  </div>
               </div>
         </div>
         <div class="form-group">
              <label for="quantiteCommande">Quantité commandée</label>
              <input type="text" class="form-control" id="quantiteCommande" name="quantiteCommande" #quantiteCommande="ngModel" [(ngModel)]="model.quantiteCommande" [pattern]="digitPattern">
              <div *ngIf="quantiteCommande.errors">
                  <div [hidden]="!quantiteCommande.errors.pattern" class="alert alert-danger">
                        Quantité de commande doit être digit
                  </div>
              </div>
         </div>
         <div class="form-group">
              <label for="reapprovisionnement">Réapprovisionnement</label>
              <input type="text" class="form-control" id="reapprovisionnement" name="reapprovisionnement" #reapprovisionnement="ngModel" [(ngModel)]="model.reapprovisionnement" [pattern]="digitPattern">
              <div *ngIf="reapprovisionnement.errors">
                  <div [hidden]="!reapprovisionnement.errors.pattern" class="alert alert-danger">
                        Quantité réapprovisionnement doit être digit
                  </div>
              </div>
         </div>
         <div class="hpanel hblue">
               <div class="panel-heading hbuilt"><strong>Discontinue</strong></div>
               <div class="panel-body" style="height:60px;">
                   <div class="form-group">
                      <label class="form-check-inline">
                          <input class="form-check-input" type="radio" name="discontinue" [value]="true" [(ngModel)]="model.discontinue">&nbsp;Oui
                      </label>&nbsp;&nbsp;
                      <label class="form-check-inline">
                           <input class="form-check-input" type="radio" name="discontinue" [value]="false" [(ngModel)]="model.discontinue">&nbsp;Non
                       </label>
                    </div>
               </div>
         </div>
         <button type="submit" class="btn btn-success" [disabled]="!produitForm.form.valid">
                <i class="fa fa-check-square-o" style="font-size:24px;float:left;"></i>
                <span style="margin-left:5px;font-weight:bold;font-size:18px;">OK</span>
         </button>&nbsp;
         <button class="btn btn-success" onclick="window.location.href='/produit';return false;">
                 <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                 <span style="margin-left:5px;font-weight:bold;font-size:18px;">BACK</span>
        </button>
    </form>
</article>
