// vue.js/src/components/produit/liste.vue
<template>
    <div>
        <article>
            <div class="row" style="margin-bottom:20px;">
                <div class="col-lg-12">
                    <router-link :to="{ path: 'new'}" append class="btn btn-primary">Nouveau</router-link>
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col-lg-9">
                    <span style="font-size:25px;"><strong>Liste des produits</strong></span>
                </div>
            </div>
            <div class="row">
                <table class="table table-bordered" cellspacing="1" cellpadding="1">
                    <thead>
                        <tr>
                            <th v-for="value in title" v-bind:class="center">{{value}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="produit in produits">
                            <td v-bind:class="center" ><a href="#" @click.prevent="removeProduit(produit._id)">Supprimer</a></td>
                            <td v-bind:class="center"><router-link :to="{ path: produit._id}" append>Modifier</router-link></td>
                            <td>{{ produit.nom }}</td>
                            <td>{{ produit.category[0].nom }}</td>
                            <td>{{ produit.fournisseur.compagnie }}</td>
                            <td v-bind:class="right">{{ produit.quantite }}</td>
                            <td v-bind:class="right">{{ produit.prix | currency}}</td>
                            <td v-bind:class="right">{{ produit.quantiteRestante }}</td>
                            <td v-bind:class="right">{{ produit.quantiteCommande }}</td>
                            <td v-bind:class="right">{{ produit.reapprovisionnement }}</td>
                            <td v-bind:class="center">
                                <span v-html="htmlTag(produit.discontinue)"></span>
                            </td>
                            <td v-bind:class="center">
                                <span v-html="htmlTag(produit.active)"></span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </article>
    </div>
</template>

<script>

import { ProduitService } from '../../services/produit';
import { htmlTag } from '../../inc/helper';

export default {
    name: 'ListeProduit',
    data () {
        return {
            produits:[],
            title: [
                    '',
                    '',
                    'Nom',
                    'Catégorie',
                    'Fournisseur',
                    'Quantité',
                    'Prix',
                    'Quantité restante',
                    'Quantité commandée',
                    'Réapprovisionnement',
                    'Discontinue',
                    'Active'
                ],
            center:{colCenter:true},
            right:{colRight:true},
            produitService : new ProduitService(this.$http)
        }
    },
    methods :{
        htmlTag : function(value)
        {
            return htmlTag(value);
        },
        removeProduit(produitId)
        {
            if(confirm("Êtes-vous sûre de vouloir supprimer ce produit?"))
            {
                this.produitService.removeProduitById(produitId).then(data => data?this.response(this):alert('Félicitation! Produit a été supprimé avec sans succès'));
            }
        },
        response(obj)
        {
            alert('Félicitation! Produit a été supprimé avec succès');
            obj.produitService.produitListe().then( data => obj.produits = data.body);
        }
    },
    created() 
    {
        this.produitService.produitListe().then(function(data)
        {
            var produits = data.body;
            this.produits = produits.length > 0?produits:"";
        });
    }
 
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// angular/src/app/produit/liste.component.ts
/*
* Program : Liste des produits
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from '@angular/core';
import { ProduitService } from 'src/services/produit.service';
import { IProduit } from 'src/interfaces/produit';

@Component({
  selector: 'app-produit',
  template: `
  <article>
        <div class="row" style="margin-bottom:20px;">
            <div class="col-lg-12">
                  <a class="btn btn-primary" routerLink="{{'new'}}">Nouveau</a>&nbsp;
            </div>
        </div>
        <div class="row" style="margin-bottom:20px;">
            <div class="col-lg-9">
                  <span style="font-size:25px;"><strong>Liste des produits</strong></span>
            </div>
            <div class="col-lg-3">
                    <div class="row">
                          <p class="col-lg-3"><label for="search" >Chercher</label></p>
                          <p><input type="search" size=40 [(ngModel)]="motAChercher"></p>
                    </div>
                    <div class="row">
                        <label for="search">Chercher par:</label>&nbsp;
                        <span *ngFor="let item of filtreParams">
                             <input type="checkbox" id="{{item.type}}" [(ngModel)]="item.isChecked" (change)="checkValue($event);">&nbsp;{{item.type}}
                        </span>
                    </div>
            </div>
        </div>
        <div class="row">
            <table class="table table-bordered" cellspacing="1" cellpadding="1">
               <thead>
                  <tr>
                    <th *ngFor="let value of title" [ngClass]="center">{{value}}</th>
                  </tr>
              </thead>
              <tbody *ngFor="let produit of produits | filtreProduit:filtreParams:motAChercher">
                 <tr>
                     <td [ngClass]="center"><a href="#" (click)="removeProduit($event,produit._id)">Supprimer</a></td>
                     <td [ngClass]="center"><a routerLink="{{produit._id}}">Modifier</a></td>
                     <td>{{ produit.nom }}</td>
                     <td>{{ produit.category[0].nom }}</td>
                     <td>{{ produit.fournisseur.compagnie }}</td>
                     <td [ngClass]="right">{{ produit.quantite }}</td>
                     <td [ngClass]="right">{{ produit.prix | currency }}</td>
                     <td [ngClass]="right">{{ produit.quantiteRestante }}</td>
                     <td [ngClass]="right">{{ produit.quantiteCommande }}</td>
                     <td [ngClass]="right">{{ produit.reapprovisionnement }}</td>
                     <td [ngClass]="center">
                          <span [innerHTML]="produit.discontinue | filtreHtmlTag:'check-square-icon'"></span>
                     </td>
                     <td [ngClass]="center">
                          <span [innerHTML]="produit.active | filtreHtmlTag:'check-square-icon'"></span>
                     </td>
                  </tr>
               </tbody>
            </table>
        </div>
  </article>
  <router-outlet></router-outlet>
  `,
  styles: []
})
export class ListeProduitComponent implements OnInit {

  public produits:IProduit[] = [];
  public filtreParams:any[] = [];
  public motAChercher:string = "";
  public title:string[] = [
                              '',
                              '',
                              'Nom',
                              'Catégorie',
                              'Fournisseur',
                              'Quantité',
                              'Prix',
                              'Quantité restante',
                              'Quantité commandée',
                              'Réapprovisionnement',
                              'Discontinue',
                              'Active'
                          ];
  public right:any={colRight:true};
  public center:any={colCenter:true};

  constructor(private _produitService:ProduitService) { }

  ngOnInit()
  {
       this.filtreParams = [
                              { type : 'nom', isChecked : true},
                              { type : 'catégorie', isChecked : false},
                              { type : 'Quantité', isChecked : false},
                              { type : 'Prix', isChecked : false},
                            ];

       this._produitService.getProduitList().subscribe( data => this.produits = data);
  }
  removeProduit(event:any,produitId:string):void
  {
      if(confirm("Êtes-vous sûre de vouloir supprimer ce produit?"))
      {
          this._produitService.removeProduitById(produitId).subscribe(data => this.response(data));
      }
      event.preventDefault();
  }
  response(data:IProduit):void
  {
      if(data)
      {
          alert('Félicitation! Produit a été supprimé avec succès');
          this._produitService.getProduitList().subscribe( data => this.produits = data);
      }
  }
  checkValue(event:any):void
  {
       this.motAChercher = "";
       this.filtreParams.map(function(value){
           if(value.type.match(event.target.id))
           {
               value.isChecked = event.target.checked;
           }
           return value;
       });
   }
}
