// angular/src/app/categorie/detail.component.ts
/*
* Program : Liste des catégories
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from '@angular/core';
import { CategorieService } from 'src/services/categorie.service';
import { ProduitService } from 'src/services/produit.service';
import { IProduit } from 'src/interfaces/produit';
import { ActivatedRoute, Router } from '@angular/router';
import { Categorie } from 'src/classes/categorie';
import { FileUpload } from 'src/classes/fileUpload';
import { ICategorie } from 'src/interfaces/categorie';
import { Regex } from 'src/classes/regex';

@Component({
  selector: 'app-categorie',
  templateUrl: './detail.component.html',
  styles: [`
              #categorieDetail .row
              {
                  margin: 0 0 5px 0;
              }
          `]
})

export class DetailCategorieComponent implements OnInit {

  public model:Categorie;
  public nodigitPattern:string = Regex.NoDigitPattern();
  public uploadStatus:boolean = false;
  public titre:string;
  private file:string;
  private id:string;
  public fileToUpload:FileUpload = new FileUpload();

  constructor(private _categorieService:CategorieService,
              private _produitService:ProduitService,
              private route: ActivatedRoute,
              private router: Router) {}

  ngOnInit()
  {
      this.id = this.route.snapshot.params.id;
      this.model = new Categorie();
      this.titre = "Ajouter";
      if(this.id)
      {
          this.titre = "Modifier";
          this._categorieService.getCategorieById(this.id).subscribe(data => this.response(this,data));
      }
  }
  response(obj,data):void
  {
      obj.model._id = data._id;
      obj.model.nom = data.nom;
      obj.model.description = data.description;
      obj.model.photo = data.photo;
      obj.model.active = data.active;
  }
  onSubmit():void
  {
      if(this.id)
      {
          this._categorieService.updateCategorie(this.id,this.model)
                                .subscribe(data => this.responseSaveCategorie(this,data,this.model));
      }else{
          this._categorieService.saveCategorie(this.model)
                                .subscribe(data => data?this.router.navigateByUrl('/admin/categorie'):"");
      }
   }
   responseSaveCategorie(obj:DetailCategorieComponent,OldCategorie:ICategorie,NewCategorie:ICategorie):void
   {
        let that:DetailCategorieComponent = obj;
        obj._produitService.getProduitList()
                            .subscribe(function(produits){
                                  that.router.navigateByUrl('/admin/categorie');
                                  let produitBD:IProduit[] = produits.filter(data => data.category[0]._id == OldCategorie._id);
                                  if(produitBD.length > 0)
                                      that.updateProduit(that,produitBD,NewCategorie);
                            });
   }
   updateProduit(obj:DetailCategorieComponent,produits:IProduit[],categorie:ICategorie):void
   {
       produits.forEach(function(produit)
       {
            produit.category[0] = categorie;
            obj._produitService.updateProduit(produit._id,produit)
                               .subscribe(data => data);
       });
   }
}

<article id="categorieDetail">
    <h1>{{ titre }} la catégorie</h1>
    <form (ngSubmit)="onSubmit()" #categorieForm="ngForm">
         <div class="row">
             <div class="col-md-3">
                 <label class="control-label" for="nom">Nom</label>&nbsp;<span style="color:red;">*</span>
                 <input type="text" class="form-control" id="nom" name="nom" #nom="ngModel" required [(ngModel)]="model.nom" [pattern]="nodigitPattern">
                 <div *ngIf="nom.errors">
                       <div [hidden]="!nom.errors.required || nom.pristine" class="alert alert-danger">
                             Nom est obligatoire
                       </div>
                       <div [hidden]="!nom.errors.pattern" class="alert alert-danger">
                             Nom contient seulement des caractères
                       </div>
                 </div>
             </div>
         </div>
         <div class="row">
              <div class="col-md-3">
                  <label class="control-label" for="description">Description</label>
                  <input type="text" class="form-control" id="description" [(ngModel)]="model.description" name="description">
              </div>
         </div>
         <div class="row">
              <div class="col-md-3">
                  <label class="control-label" for="image">Image</label>
                  <app-file-upload
                      name="image"
                      maxFiles="1"
                      maxSize="2"
                      fileExt="JPG, GIF, PNG, JPEG"
                      (uploadStatus)="refreshImage($event)"
                      (FileToSave)="FileToSave($event)">
                  </app-file-upload>
              </div>
         </div>
         <div class="row">
               <div class="col-md-3">
                   <div class="well" *ngIf="model.photo">
                      <div class="parent">
                          <img [src]="model.photo" [alt]="model.nom" [height]="height" [width]="width"/>
                          <button class="btn btn-danger"
                                  [style.display]="!uploadStatus?'none':'inherit'"
                                  style="position:absolute;top:0;right:0;border-radius:10px;margin:1px 2px 0px 0px;"
                                  (click)="removeImage($event)">X
                          </button>
                        </div>
                   </div>
                </div>
          </div>
          <div class="row">
                <div class="col-md-8">
                     <button type="submit" class="btn btn-success" [disabled]="!categorieForm.form.valid">
                           <i class="fa fa-check-square-o" style="font-size:24px;float:left;"></i>
                           <span style="margin-left:5px;font-weight:bold;font-size:18px;">OK</span>
                     </button>&nbsp;
                     <button class="btn btn-success" onclick="window.location.href='/admin/categorie';return false;">
                            <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                            <span style="margin-left:5px;font-weight:bold;font-size:18px;">BACK</span>
                     </button>
                </div>
                <div class="form-group">
                   <input type="hidden" class="form-control" id="active" [(ngModel)]="model.active" name="active">
                </div>
         </div>
    </form>
</article>

// vue.js/src/components/categorie/detail.vue
<template>
    <div>
        <article class="col-sm-4">
            <h1>{{ titre }} la catégorie</h1>
            <form v-on:submit.prevent="onSubmit">
                <div class="form-group">
                    <label class="control-label" for="nom">Nom</label>
                    <input class="form-control" name="nom" v-model.trim="$v.nom.$model"/>
                    <div v-if="!$v.nom.required" class="alert alert-danger">Nom est obligatoire</div>
                    <div v-if="!$v.nom.alpha" class="alert alert-danger">Nom contient seulement des caractères</div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="description">Description</label>
                    <input type="text" name="description" class="form-control" v-model="model.description">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <app-file-upload 
                            maxFiles = 1
                            maxSize = 2
                            fileExt ="JPG, GIF, PNG, JPEG"
                            v-on:UploadStatus="UploadStatus($event)" 
                            v-on:FileToSave="FileToSave($event)">
                    </app-file-upload>
                </div>
                <div class="well" v-if="model.image">
                    <div class="parent">
                        <img v-bind:src="model.image" :alt="model.nom" :height="height" :width="width" />
                        <button class="btn btn-danger"
                                :style="styleXRemove"
                                @click.prevent="removeImage">X
                        </button>
                    </div>
                </div>
                <div class="form-group">
                    <input type="hidden" class="form-control" name="active" v-model="model.active">
                </div>
                <button type="submit" class="btn btn-success" :disabled="!$v.nom.required || !$v.nom.alpha">
                    <i class="fa fa-check-square-o" style="font-size:24px;float:left;"></i>
                    <span style="margin-left:5px;font-weight:bold;font-size:18px;">OK</span>
                </button>&nbsp;
                <button class="btn btn-success" onclick="window.location.href='/admin/categorie';return false;">
                    <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                    <span style="margin-left:5px;font-weight:bold;font-size:18px;" >BACK</span>
                </button>
            </form>
        </article>
    </div>
</template>

<script>

import { CategorieService } from '../../services/categorie';
import { ProduitService } from '../../services/produit';
import { alpha } from '../../inc/helper';
import { Categorie } from '../../classes/categorie';
import { required } from 'vuelidate/lib/validators';
import  fileUpload  from '../file-upload';

const HEIGHT = 135, WIDTH = 192, NONE = 0;

export default {
    name: 'CategorieDetail',
    components : {
        'app-file-upload' : fileUpload
    },
    data () {
        return {
            categories : [],
            titre : "Ajouter",
            center:{colCenter:true},
            nom : "",
            uploadStatus : 0,
            model : new Categorie(),
            height : HEIGHT,
            width : WIDTH,
            styleXRemove : {
                position:'absolute',
                top:0,
                right:0,
                borderRadius:'10px',
                margin:'1px 2px 0px 0px',
                display : 'inherit'
            },
            categorieService : new CategorieService(this.$http), 
            produitService : new ProduitService(this.$http)
        }
    },
    
    created()
    {
        if(this.$route.params.id)
        {   
            this.categorieService.getCategorieById(this.$route.params.id).then(function(data)
            {
                var categories = data.body;
                categories = typeof categories === 'object'?categories:"";
                this.model = categories;
                this.nom = this.model.nom;
                this.image = this.model.image;
                this.titre = "Modifier";
            });
        }
    },
    methods : {
        UploadStatus(uploadStatus)
        {
            this.uploadStatus = uploadStatus; 
        },
        FileToSave(file)
        {
            if(this.uploadStatus)
            {
                this.model.image = file;
                this.styleXRemove.display = 'inherit';
                this.height = HEIGHT;
                this.width = WIDTH;
            }
        },
        onSubmit : function()
        {
            if(this.$route.params.id)
            {
                this.model.nom = this.nom;
                this.categorieService.updateCategorie(this.$route.params.id,this.model)
                                .then(data => this.responseSaveCategorie(this,
                                              this.produitService,
                                              data.body,
                                              this.model));
            }else
            {
                var obj = new Object();
                obj.nom = this.nom;
                obj.description = this.model.description;
                obj.image = this.model.image;
                obj.dateCreation = this.model.dateCreation;
                obj.active = this.model.active;
                this.categorieService.saveCategorie(obj).then(data => data?this.$router.push({ name: "ListeCategorie"}):"");
            }    
        },
        removeImage : function()
        {
            this.model.image = "";
            this.height = NONE;
            this.width = NONE;
            this.styleXRemove.display = 'none';
            this.uploadStatus = 0;
        },
        responseSaveCategorie(obj,produitService,OldCategorie,NewCategorie)
        {
            var that = obj;
            produitService.produitListe().then(function(produits)
            {
                var produitBD = produits.body.filter(produit => produit.category[0]._id == OldCategorie._id);
                if(produitBD.length > 0)
                    that.updateProduit(that,produitService,produitBD,NewCategorie);
            });
            obj.$router.push({ name: "ListeCategorie"});
        },
        updateProduit(obj,produitService,produitBD,NewCategorie)
        {
            produitBD.forEach(function(produit)
            {
                produit.category[0] = NewCategorie;
                produitService.updateProduit(produit._id,produit).then(data => data);
            });
        },
    },
    validations : {
        nom : {
            required,
            alpha
        }
    }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.parent {
            position: relative;
            display: inline-block;
        }
</style>
