// angular/src/app/home/home.component.ts
/*
Program : Youtube tutorial
Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import * as func from 'src/inc/tutoriel';
import { Tuto } from 'src/classes/tuto';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styles: [`
              #main .title{
                text-align:left;
              }
              #previous{
                  float:left;
              }
              #next{
                  float:right;
              }
              .titre{
                  min-height:50px;
                  padding:10px;
                  font-weight:bold;
                  font-size:20px;
                  text-align:center;
              }
          `]
})
export class HomeComponent implements OnInit {

  public ngCodeEvolution:Tuto;
  public NgTheNetNinja:Tuto;

  constructor(private _sanitizer: DomSanitizer) {}

  ngOnInit() {
      this.ngCodeEvolution = new Tuto(func.NgCodeEvolution()[0],this._sanitizer);
      this.NgTheNetNinja = new Tuto(func.NgCodeEvolution()[1],this._sanitizer);
  }

}

<section id="main">
   <div class="hpanel col-md-9">
        <div class="panel-heading hbuilt">
             <div class="panel-tools">
                   <a class="showhide"><i class="fa fa-chevron-up"></i></a>
             </div>
             Formations
        </div>
        <div class="panel-body">
           <div class="row">
               <div class="col-lg-6 border-right">
                      <label class="col-sm-2 control-label">Vidéo : </label>
                      <select [(ngModel)]="ngCodeEvolution.itemSelected" (change)="ngCodeEvolution.selectedItem()">
                            <option *ngFor="let item of ngCodeEvolution.listItem();let i = index" value={{item.id}}>{{ i + 1 }} - {{ item.titre}}</option>
                      </select>
                      <h2 class="title"><strong>Introduction Angular 6</strong></h2>
                      <p>
                            <iframe width="585" height="315" [src]="ngCodeEvolution.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                      </p>
                      <p class="titre">
                          <span>Tutorial #{{ngCodeEvolution.count}} - {{ ngCodeEvolution.titre }}</span>
                      </p>
                      <p>
                          <button type="button" class="btn btn-primary" id="previous"  (click)="ngCodeEvolution.previous()">Précédent</button>
                          <button type="button" class="btn btn-primary" id="next" (click)="ngCodeEvolution.next()">Suivant</button>
                      </p>
                </div>
                <div class="col-lg-6">
                      <label class="col-sm-2 control-label">Vidéo : </label>
                      <select [(ngModel)]="NgTheNetNinja.itemSelected" (change)="NgTheNetNinja.selectedItem()">
                            <option *ngFor="let item of NgTheNetNinja.listItem();let i = index" value={{item.id}}>{{ i + 1}} - {{ item.titre}}</option>
                      </select>
                      <h2 class="title"><strong>Introduction Angular 2</strong></h2>
                      <p>
                            <iframe width="590" height="315" [src]="NgTheNetNinja.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                      </p>
                      <p class="titre">
                          <span>Tutorial #{{NgTheNetNinja.count}} - {{ NgTheNetNinja.titre }}</span>
                      </p>
                      <p>
                          <button type="button" class="btn btn-primary" id="previous"  (click)="NgTheNetNinja.previous()">Précédent</button>
                          <button type="button" class="btn btn-primary" id="next" (click)="NgTheNetNinja.next()">Suivant</button>
                      </p>
                </div>
           </div>
         </div>
    </div>
</section>

// php/laravel/resources/assets/js/components/homeComponent.vue
<template>
    <section id="main">
        <div class="hpanel col-md-9">
            <div class="panel-heading hbuilt">
                <div class="panel-tools">
                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                </div>
                Vue JS 2, TypeScript Basics
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6 border-right">
                        <label class="col-sm-2 control-label">Vidéo : </label>
                        <select v-model="tutoriels.Vuejs2.itemSelected" v-on:change="tutoriels.Vuejs2.selectedItem()">
                                <option v-for="(item,index) in tutoriels.Vuejs2.listItem()" v-bind:value="item.id">{{ index + 1 }} - {{ item.titre}}</option>
                        </select>
                        <h2 class="title"><strong>Vue JS 2</strong></h2>
                        <p>
                                <iframe width="580" height="315" v-bind:src="tutoriels.Vuejs2.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        </p>
                        <p class="titre">
                            <span>{{tutoriels.Vuejs2.count}} - {{ tutoriels.Vuejs2.titre }}</span>
                        </p>
                        <p>
                            <button type="button" class="btn btn-primary" id="previous"  v-on:click="tutoriels.Vuejs2.previous()">Précédent</button>
                            <button type="button" class="btn btn-primary" id="next" v-on:click="tutoriels.Vuejs2.next()">Suivant</button>
                        </p>
                    </div>
                    <div class="col-lg-6">
                        <label class="col-sm-2 control-label">Vidéo : </label>
                        <select v-model="tutoriels.TypeScriptBasic.itemSelected" v-on:change="tutoriels.TypeScriptBasic.selectedItem()">
                                <option v-for="(item,index) in tutoriels.TypeScriptBasic.listItem()" v-bind:value="item.id">{{ index + 1 }} - {{ item.titre}}</option>
                        </select>
                        <h2 class="title"><strong>TypeScript Basics</strong></h2>
                        <p>
                                <iframe width="580" height="315" v-bind:src="tutoriels.TypeScriptBasic.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        </p>
                        <p class="titre">
                            <span>{{tutoriels.TypeScriptBasic.count}} - {{ tutoriels.TypeScriptBasic.titre }}</span>
                        </p>
                        <p>
                            <button type="button" class="btn btn-primary" id="previous"  v-on:click="tutoriels.TypeScriptBasic.previous()">Précédent</button>
                            <button type="button" class="btn btn-primary" id="next" v-on:click="tutoriels.TypeScriptBasic.next()">Suivant</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="hpanel col-md-9">
            <div class="panel-heading hbuilt">
                <div class="panel-tools">
                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                </div>
                Node JS, PHP7 New Features
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6 border-right">
                        <label class="col-sm-2 control-label">Vidéo : </label>
                        <select v-model="tutoriels.Nodejs.itemSelected" v-on:change="tutoriels.Nodejs.selectedItem()">
                                <option v-for="(item,index) in tutoriels.Nodejs.listItem()" v-bind:value="item.id">{{ index + 1 }} - {{ item.titre}}</option>
                        </select>
                        <h2 class="title"><strong>Node JS</strong></h2>
                        <p>
                                <iframe width="580" height="315" v-bind:src="tutoriels.Nodejs.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        </p>
                        <p class="titre">
                            <span>{{tutoriels.Nodejs.count}} - {{ tutoriels.Nodejs.titre }}</span>
                        </p>
                        <p>
                            <button type="button" class="btn btn-primary" id="previous"  v-on:click="tutoriels.Nodejs.previous()">Précédent</button>
                            <button type="button" class="btn btn-primary" id="next" v-on:click="tutoriels.Nodejs.next()">Suivant</button>
                        </p>
                    </div>
                    <div class="col-lg-6">
                         <label class="col-sm-2 control-label">Vidéo : </label>
                            <select v-model="tutoriels.PHP7.itemSelected" v-on:change="tutoriels.PHP7.selectedItem()">
                                    <option v-for="(item,index) in tutoriels.PHP7.listItem()" v-bind:value="item.id">{{ index + 1 }} - {{ item.titre}}</option>
                            </select>
                            <h2 class="title"><strong>PHP7 New Features</strong></h2>
                            <p>
                                    <iframe width="580" height="315" v-bind:src="tutoriels.PHP7.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                            </p>
                            <p class="titre">
                                <span>{{tutoriels.PHP7.count}} - {{ tutoriels.PHP7.titre }}</span>
                            </p>
                            <p>
                                <button type="button" class="btn btn-primary" id="previous"  v-on:click="tutoriels.PHP7.previous()">Précédent</button>
                                <button type="button" class="btn btn-primary" id="next" v-on:click="tutoriels.PHP7.next()">Suivant</button>
                            </p>    
                    </div>  
                </div>
            </div>
        </div>
        <div class="hpanel col-md-9">
            <div class="panel-heading hbuilt">
                <div class="panel-tools">
                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                </div>
                Python 3 for beginners, Python OOP, 
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6 border-right">
                        <label class="col-sm-2 control-label">Vidéo : </label>
                        <select v-model="tutoriels.Python3.itemSelected" v-on:change="tutoriels.Python3.selectedItem()">
                                <option v-for="(item,index) in tutoriels.Python3.listItem()" v-bind:value="item.id">{{ index + 1 }} - {{ item.titre}}</option>
                        </select>
                        <h2 class="title"><strong>Python 3 for beginners</strong></h2>
                        <p>
                                <iframe width="580" height="315" v-bind:src="tutoriels.Python3.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        </p>
                        <p class="titre">
                            <span>{{tutoriels.Python3.count}} - {{ tutoriels.Python3.titre }}</span>
                        </p>
                        <p>
                            <button type="button" class="btn btn-primary" id="previous"  v-on:click="tutoriels.Python3.previous()">Précédent</button>
                            <button type="button" class="btn btn-primary" id="next" v-on:click="tutoriels.Python3.next()">Suivant</button>
                        </p>
                    </div>
                    <div class="col-lg-6">
                        <label class="col-sm-2 control-label">Vidéo : </label>
                        <select v-model="tutoriels.PythonOOP.itemSelected" v-on:change="tutoriels.PythonOOP.selectedItem()">
                                <option v-for="(item,index) in tutoriels.PythonOOP.listItem()" v-bind:value="item.id">{{ index + 1 }} - {{ item.titre}}</option>
                        </select>
                        <h2 class="title"><strong>Python OOP</strong></h2>
                        <p>
                                <iframe width="580" height="315" v-bind:src="tutoriels.PythonOOP.url" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        </p>
                        <p class="titre">
                            <span>{{tutoriels.PythonOOP.count}} - {{ tutoriels.PythonOOP.titre }}</span>
                        </p>
                        <p>
                            <button type="button" class="btn btn-primary" id="previous"  v-on:click="tutoriels.PythonOOP.previous()">Précédent</button>
                            <button type="button" class="btn btn-primary" id="next" v-on:click="tutoriels.PythonOOP.next()">Suivant</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script>

import Tuto from '../classes/tuto';
import youtubeEmbedUrls from '../inc/tutoriel';

export default {
        name: 'Home',
        data () {
            return {
                    tutoriels:{}
                }
        },
        created(){
            var i = 0;
            this.tutoriels = {
                    "Vuejs2" : new Tuto(youtubeEmbedUrls()[i]),
                    "TypeScriptBasic" : new Tuto(youtubeEmbedUrls()[++i]),
                    "Nodejs" : new Tuto(youtubeEmbedUrls()[++i]),
                    "Python3" : new Tuto(youtubeEmbedUrls()[++i]),
                    "PythonOOP" : new Tuto(youtubeEmbedUrls()[++i]),
                    "PHP7" : new Tuto(youtubeEmbedUrls()[++i]),
            };    
        }
  }
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
    #main .title{
        text-align:left;
        }
    #previous{
        float:left;
    }
    #next{
        float:right;
    }
    .titre{
        min-height:50px;
        padding:10px;
        font-weight:bold;
        font-size:18px;
        text-align:center;
        border:1px solid #ccc;
    }
</style>
