// vue.js/src/components/shoppingCart/addToCart.vue
<template>
    <article>
        <div class="hpanel hblue">
            <div class="panel-heading hbuilt"><strong>Votre Panier</strong></div>
            <div class="panel-body">
                <div class="col-sm-8" v-if="carts.length > 0">
                    <table class="table table-bordered" role="grid">
                        <thead>
                            <tr>
                                <th v-for="header in ['Nom','Quantité','Prix','Total','']" :class="center">{{header}}</th>
                            </tr>
                        </thead>
                        <tbody>
                        <tr v-for="cart in carts">
                                <td>{{cart.nom}}</td>
                                <td :class="right" style="width:10%;"><input type="text" :id="cart._id" size="3" :value="cart.quantite"></td>
                                <td :class="right" style="width:10%;">{{ cart.prix | currency }}</td>
                                <td :class="right" style="width:20%;">{{ cart.total | currency }}</td>
                                <td style="width:18%;">
                                    <button type="submit" class="btn btn-success" @click="updateCart(cart._id)">Modifier</button>&nbsp;
                                    <button type="submit" class="btn btn-danger" @click="removeCart(cart._id)">Enlever</button>
                                </td>
                        </tr>
                        <tr>
                               <td colspan="3"></td>
                               <td>
                                   <table class="table table-border">
                                       <tr>
                                           <td><strong>Total:</strong></td>
                                           <td style="text-align:right;"><strong>{{ Total | currency}}</strong></td>
                                       </tr>
                                       <tr>
                                           <td><strong>TPS({{TPS}}%):</strong></td>
                                           <td style="text-align:right;"><strong>{{ TaxeTPS | currency}}</strong></td>
                                       </tr>
                                       <tr>
                                           <td><strong>TVQ({{TVQ}}%):</strong></td>
                                           <td style="text-align:right;"><strong>{{ TaxeTVQ | currency}}</strong></td>
                                       </tr>
                                       <tr>
                                           <td><strong>Grande Total:</strong></td>
                                           <td style="text-align:right;"><strong>{{ GrandeTotal | currency}}</strong></td>
                                       </tr>
                                    </table>
                               </td>
                        </tr>       
                        </tbody>
                    </table>
                </div>
                <div v-else>Votre panier est vide</div>
            </div>
        </div>  
        <div>
            <router-link :to="{ path: '/shoppingcart'}" append class="btn btn-info">
                <i class="fa fa-backward" style="font-size:24px;float:left;"></i>
                <span style="margin-left:5px;font-weight:bold;font-size:18px;">Continue magasiner</span>
            </router-link>
        </div>
    </article>
</template>

<script>

import { LocalStorage } from '../../classes/localstorage';

export default {  
    name: 'AddToCart',
   
    data () {
        return {
            carts : [],
            localStorage : new LocalStorage(),
            TPS : 9.15,
            TVQ : 7.13,
            center:{colCenter:true},
            right:{colRight:true},
        }
    },
    created()
    {
        this.carts = this.localStorage.getItem('carts');
    },
    computed : {
          Total()
          {
             return this.calcTotal();
          },
          TaxeTPS()
          {
             return this.calcTPS();
          },
          TaxeTVQ()
          {
             return this.calcTVQ();
          },
          GrandeTotal()
          {
              return parseFloat(this.calcTotal()) + parseFloat(this.calcTPS()) + parseFloat(this.calcTVQ());
          }
    },
    methods : {
        calcTotal()
        {
            var total = 0;
            var len = this.carts.length;
            for(var i=0;i<len;i++)
            {
                total += parseFloat(this.carts[i].total);
            }
            return total;
        },
        calcTPS()
        {
            return parseFloat((this.calcTotal() * this.TPS) / 100).toFixed(2);
        },
        calcTVQ()
        {
            return parseFloat((this.calcTotal() * this.TVQ) / 100).toFixed(2);
        },
        updateCart(cartId)
        {
            var quantite = parseInt(document.getElementById(cartId).value);
            if(!quantite)
            {
                alert('Désolé! Veuillez entrer une quantité');
                return;
            }
            this.carts.map(function(value){
                 if(value._id.indexOf(cartId) !== -1)
                 {
                      value.quantite = quantite;
                      value.total = parseFloat(value.prix * value.quantite);
                      return value;
                 }
            });
            this.localStorage.setItem('carts',this.carts);   
        },
        removeCart(cartId)
        {
            if(confirm('Êtes-vous sûre de vouloir supprimer ce item?'))
            {
                this.carts = this.carts.filter(data => data._id.indexOf(cartId) == -1);
                this.localStorage.setItem('carts',this.carts); 
            }
        }
    }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// angular/src/components/shoppingCart/add-to-cart.component.ts
/*
* Program : addTocart component
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from "@angular/core";
import { LocalStorage } from "../../classes/localstorage";
import { ShoppingCart } from "../../classes/shoppingcart";

@Component({
  selector: "app-add-to-cart",
  templateUrl: "../../view/shoppingCart/add-to-cart.html",
  styleUrls: []
})
export class AddToCartComponent implements OnInit {
  public carts: Array<ShoppingCart> = [];
  public TPS: number = 9.15;
  public TVQ: number = 7.13;
  public center: any = { colCenter: true };
  public right: any = { colRight: true };

  constructor() {}

  ngOnInit() {
    this.carts = LocalStorage.getItem("carts");
  }
  Total(): number {
    return this.calcTotal();
  }
  TaxeTPS(): number {
    return this.calcTPS();
  }
  TaxeTVQ(): number {
    return this.calcTVQ();
  }
  GrandeTotal(): number {
    return this.calcTotal() + this.calcTPS() + this.calcTVQ();
  }
  calcTotal(): number {
    var total: number = 0;
    var len = this.carts.length;
    for (var i = 0; i < len; i++) {
      total += this.carts[i].total;
    }
    return total;
  }
  calcTPS(): number {
    return (this.calcTotal() * this.TPS) / 100;
  }
  calcTVQ(): number {
    return (this.calcTotal() * this.TVQ) / 100;
  }
  updateCart(cartId): void {
    var quantite = parseInt(
      (<HTMLInputElement>document.getElementById(cartId)).value
    );
    if (!quantite) {
      alert("Désolé! Veuillez entrer une quantité");
      return;
    }
    this.carts.map(function(value) {
      if (value._id.indexOf(cartId) !== -1) {
        value.quantite = quantite;
        value.total = value.prix * value.quantite;
        return value;
      }
    });
    LocalStorage.setItem("carts", this.carts);
  }
  removeCart(cartId): void {
    if (confirm("Êtes-vous sûre de vouloir supprimer cet item?")) {
      this.carts = this.carts.filter(data => data._id.indexOf(cartId) == -1);
      LocalStorage.setItem("carts", this.carts);
    }
  }
}
