// angular/src/components/shoppingCart/add-to-cart.component.ts
/*
* Program : addTocart component
* Écrit par : Dan Duc Dao
*/

import { Component, OnInit } from "@angular/core";
import { LocalStorage } from "../../classes/localstorage";
import { ShoppingCart } from "../../classes/shoppingcart";

@Component({
  selector: "app-add-to-cart",
  templateUrl: "../../views/shoppingCart/add-to-cart.html",
  styleUrls: []
})
export class AddToCartComponent implements OnInit {
  public carts: Array<ShoppingCart> = [];
  public TPS: number = 9.15;
  public TVQ: number = 7.13;
  public center: any = { colCenter: true };
  public right: any = { colRight: true };

  constructor() {}

  ngOnInit() {
    this.carts = LocalStorage.getItem("carts");
  }
  Total(): number {
    return this.calcTotal();
  }
  TaxeTPS(): number {
    return this.calcTPS();
  }
  TaxeTVQ(): number {
    return this.calcTVQ();
  }
  GrandeTotal(): number {
    return this.calcTotal() + this.calcTPS() + this.calcTVQ();
  }
  calcTotal(): number {
    var total: number = 0;
    var len = this.carts.length;
    for (var i = 0; i < len; i++) {
      total += this.carts[i].total;
    }
    return total;
  }
  calcTPS(): number {
    return (this.calcTotal() * this.TPS) / 100;
  }
  calcTVQ(): number {
    return (this.calcTotal() * this.TVQ) / 100;
  }
  updateCart(cartId): void {
    var quantite = parseInt(
      (<HTMLInputElement>document.getElementById(cartId)).value
    );
    if (!quantite) {
      alert("Désolé! Veuillez entrer une quantité");
      return;
    }
    this.carts.map(function(value) {
      if (value.id === parseInt(cartId)) {
        value.quantite = quantite;
        value.total = value.prix * value.quantite;
        return value;
      }
    });
    LocalStorage.setItem("carts", this.carts);
  }
  removeCart(cartId): void {
    if (confirm("Êtes-vous sûre de vouloir supprimer cet item?")) {
      this.carts = this.carts.filter(data => data.id === parseInt(cartId));
      LocalStorage.setItem("carts", this.carts);
    }
  }
}

// react.js/src/components/musicstore/addToCart.jsx
/*
* Program : AddToCartComponent
* Écrit par : Dan Duc Dao
*/

import React, { Component } from "react";
import CurrencyFormat from "react-currency-format";
import { Link } from "react-router-dom";
import { LocalStorage } from "../../classes/localstorage";

export default class AddToCartComponent extends Component {
  state = {
    NumberColStyle: { textAlign: "right", width: 100 },
    thStyle: { textAlign: "center" },
    localstorage: new LocalStorage(),
    carts: []
  };
  removeItem(event) {
    event.preventDefault();
    const { localstorage } = this.state;
    if (localstorage.itemExist("cart")) {
      let carts = localstorage
        .getItem("cart")
        .filter(value => value.id !== parseInt(event.target.id));
      localstorage.setItem("cart", carts);
      this.setState({ carts: carts });
      //supprimer le panier
      if (carts.length === 0) localstorage.removeItem("cart");
    }
  }
  componentDidMount() {
    this.setState({ carts: this.props.myCart });
  }
  render() {
    const { NumberColStyle, thStyle, carts, localstorage } = this.state;
    let myCarts = [];
    if (localstorage.itemExist("cart")) {
      myCarts = localstorage.getItem("cart");
    } else {
      myCarts = carts;
    }
    let cart;
    if (myCarts.length > 0) {
      cart = (
        <table className="table table-bordered">
          <thead>
            <tr>
              <th />
              <th style={thStyle}>Nom</th>
              <th style={thStyle}>Quantité</th>
              <th style={thStyle}>Prix</th>
            </tr>
          </thead>
          <tbody>
            {myCarts.map((value, key) => (
              <tr key={key}>
                <td style={{ width: 40 }}>
                  <Link
                    {...{ id: value.id }}
                    to="#"
                    onClick={e => {
                      if (
                        window.confirm(
                          "Êtes-vous sûre de vouloir supprimer cet item?"
                        )
                      )
                        this.removeItem(e);
                    }}
                  >
                    supprimer
                  </Link>
                </td>
                <td>{value.titre}</td>
                <td style={NumberColStyle}>{value.quantite}</td>
                <td style={NumberColStyle}>
                  <CurrencyFormat
                    value={value.prix}
                    displayType={"text"}
                    thousandSeparator={true}
                    prefix={"$"}
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      );
    } else {
      cart = <span style={{ color: "red" }}>Votre panier est vide</span>;
    }
    return cart;
  }
}
